
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aiotorrent-fastapi-pvc
  labels:
    app: aiotorrent-fastapi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
