
apiVersion: v1
kind: Service
metadata:
  name: aiotorrent-fastapi-service
  labels:
    app: aiotorrent-fastapi
spec:
  selector:
    app: aiotorrent-fastapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
